export const headerMapping = {
    SEASON_YEAR: "N/A",
    PLAYER_ID: "N/A",
    PLAYER_NAME: "N/A",
    NICKNAME: "N/A",
    TEAM_ID: "N/A",
    TEAM_ABBREVIATION: "N/A",
    TEAM_NAME: "N/A",
    GAME_ID: "N/A",
    GAME_DATE: "DATE",
    MATCHUP: "MATCH",
    WL: "WL",
    MIN: "MIN",
    FGM: "FGM",
    FGA: "FGA",
    FG_PCT: "FG%",
    FG3M: "3PM",
    FG3A: "3PA",
    FG3_PCT: "3P%",
    FTM: "FTM",
    FTA: "FTA",
    FT_PCT: "FT%",
    OREB: "ORB",
    DREB: "DRB",
    REB: "TRB",
    AST: "AST",
    TOV: "TOV",
    STL: "STL",
    BLK: "BLK",
    BLKA: "BLKA",
    PF: "PF",
    PFD: "PFD",
    PTS: "PTS",
    PLUS_MINUS: "+/-",
    NBA_FANTASY_PTS: "N/A",
    DD2: "N/A",
    TD3: "N/A",
    WNBA_FANTASY_PTS: "N/A",
    // NBA_FANTASY_PTS: "FPTS",
    // DD2: "DD2",
    // TD3: "TP3",
    // WNBA_FANTASY_PTS: "WFPTS",
    GP_RANK: "N/A",
    W_RANK: "N/A",
    L_RANK: "N/A",
    W_PCT_RANK: "N/A",
    MIN_RANK: "N/A",
    FGM_RANK: "N/A",
    FGA_RANK: "N/A",
    FG_PCT_RANK: "N/A",
    FG3M_RANK: "N/A",
    FG3A_RANK: "N/A",
    FG3_PCT_RANK: "N/A",
    FTM_RANK: "N/A",
    FTA_RANK: "N/A",
    FT_PCT_RANK: "N/A",
    OREB_RANK: "N/A",
    DREB_RANK: "N/A",
    REB_RANK: "N/A",
    AST_RANK: "N/A",
    TOV_RANK: "N/A",
    STL_RANK: "N/A",
    BLK_RANK: "N/A",
    BLKA_RANK: "N/A",
    PF_RANK: "N/A",
    PFD_RANK: "N/A",
    PTS_RANK: "N/A",
    PLUS_MINUS_RANK: "N/A",
    NBA_FANTASY_PTS_RANK: "N/A",
    DD2_RANK: "N/A",
    TD3_RANK: "N/A",
    WNBA_FANTASY_PTS_RANK: "N/A",
    AVAILABLE_FLAG: "N/A",
};

export const seasonHeaderMapping = {
    SEASON_ID: "YR",
    PLAYER_ID: "N/A",
    PLAYER_NAME: "N/A",
    NICKNAME: "N/A",
    TEAM_ID: "N/A",
    TEAM_ABBREVIATION: "TM",
    // TEAM_NAME: "N/A",
    // GAME_ID: "N/A",
    // GAME_DATE: "DATE",
    // MATCHUP: "MATCH",
    PLAYER_AGE: "AGE",
    GP: "GP",
    GS: "GS",
    WL: "WL",
    MIN: "MIN",
    FGM: "FGM",
    FGA: "FGA",
    FG_PCT: "FG%",
    FG3M: "3PM",
    FG3A: "3PA",
    FG3_PCT: "3P%",
    FTM: "FTM",
    FTA: "FTA",
    FT_PCT: "FT%",
    OREB: "ORB",
    DREB: "DRB",
    REB: "TRB",
    AST: "AST",
    TOV: "TOV",
    STL: "STL",
    BLK: "BLK",
    BLKA: "BLKA",
    PF: "PF",
    PFD: "PFD",
    PTS: "PTS",
    PLUS_MINUS: "+/-",
    NBA_FANTASY_PTS: "N/A",
    DD2: "N/A",
    TD3: "N/A",
    WNBA_FANTASY_PTS: "N/A",
    // NBA_FANTASY_PTS: "FPTS",
    // DD2: "DD2",
    // TD3: "TP3",
    // WNBA_FANTASY_PTS: "WFPTS",
    GP_RANK: "N/A",
    W_RANK: "N/A",
    L_RANK: "N/A",
    W_PCT_RANK: "N/A",
    MIN_RANK: "N/A",
    FGM_RANK: "N/A",
    FGA_RANK: "N/A",
    FG_PCT_RANK: "N/A",
    FG3M_RANK: "N/A",
    FG3A_RANK: "N/A",
    FG3_PCT_RANK: "N/A",
    FTM_RANK: "N/A",
    FTA_RANK: "N/A",
    FT_PCT_RANK: "N/A",
    OREB_RANK: "N/A",
    DREB_RANK: "N/A",
    REB_RANK: "N/A",
    AST_RANK: "N/A",
    TOV_RANK: "N/A",
    STL_RANK: "N/A",
    BLK_RANK: "N/A",
    BLKA_RANK: "N/A",
    PF_RANK: "N/A",
    PFD_RANK: "N/A",
    PTS_RANK: "N/A",
    PLUS_MINUS_RANK: "N/A",
    NBA_FANTASY_PTS_RANK: "N/A",
    DD2_RANK: "N/A",
    TD3_RANK: "N/A",
    WNBA_FANTASY_PTS_RANK: "N/A",
    AVAILABLE_FLAG: "N/A",
};

export const teamHeaderMapping = {
    SEASON_YEAR: "N/A",
    PLAYER_ID: "N/A",
    PLAYER_NAME: "N/A",
    NICKNAME: "N/A",
    TEAM_ID: "N/A",
    TEAM_ABBREVIATION: "N/A",
    TEAM_NAME: "N/A",
    GAME_ID: "N/A",
    GAME_DATE: "DATE",
    MATCHUP: "MATCH",
    WL: "WL",
    MIN: "MIN",
    FGM: "FGM",
    FGA: "FGA",
    FG_PCT: "FG%",
    FG3M: "3PM",
    FG3A: "3PA",
    FG3_PCT: "3P%",
    FTM: "FTM",
    FTA: "FTA",
    FT_PCT: "FT%",
    OREB: "ORB",
    DREB: "DRB",
    REB: "TRB",
    AST: "AST",
    TOV: "TOV",
    STL: "STL",
    BLK: "BLK",
    BLKA: "BLKA",
    PF: "PF",
    PFD: "PFD",
    PTS: "PTS",
    PLUS_MINUS: "+/-",
    NBA_FANTASY_PTS: "N/A",
    DD2: "N/A",
    TD3: "N/A",
    WNBA_FANTASY_PTS: "N/A",
    // NBA_FANTASY_PTS: "FPTS",
    // DD2: "DD2",
    // TD3: "TP3",
    // WNBA_FANTASY_PTS: "WFPTS",
    GP_RANK: "N/A",
    W_RANK: "N/A",
    L_RANK: "N/A",
    W_PCT_RANK: "N/A",
    MIN_RANK: "N/A",
    FGM_RANK: "N/A",
    FGA_RANK: "N/A",
    FG_PCT_RANK: "N/A",
    FG3M_RANK: "N/A",
    FG3A_RANK: "N/A",
    FG3_PCT_RANK: "N/A",
    FTM_RANK: "N/A",
    FTA_RANK: "N/A",
    FT_PCT_RANK: "N/A",
    OREB_RANK: "N/A",
    DREB_RANK: "N/A",
    REB_RANK: "N/A",
    AST_RANK: "N/A",
    TOV_RANK: "N/A",
    STL_RANK: "N/A",
    BLK_RANK: "N/A",
    BLKA_RANK: "N/A",
    PF_RANK: "N/A",
    PFD_RANK: "N/A",
    PTS_RANK: "N/A",
    PLUS_MINUS_RANK: "N/A",
    NBA_FANTASY_PTS_RANK: "N/A",
    DD2_RANK: "N/A",
    TD3_RANK: "N/A",
    WNBA_FANTASY_PTS_RANK: "N/A",
    AVAILABLE_FLAG: "N/A",
};

export const teamSeasonHeaderMapping = {
    YEAR: "YR",
    PLAYER_ID: "N/A",
    PLAYER_NAME: "N/A",
    NICKNAME: "N/A",
    TEAM_ID: "N/A",
    TEAM_ABBREVIATION: "TM",
    // TEAM_NAME: "N/A",
    // GAME_ID: "N/A",
    // GAME_DATE: "DATE",
    // MATCHUP: "MATCH",
    PLAYER_AGE: "AGE",
    GP: "N/A",
    GS: "N/A",
    WL: "WL",
    MIN: "MIN",
    FGM: "FGM",
    FGA: "FGA",
    FG_PCT: "FG%",
    FG3M: "3PM",
    FG3A: "3PA",
    FG3_PCT: "3P%",
    FTM: "FTM",
    FTA: "FTA",
    FT_PCT: "FT%",
    OREB: "ORB",
    DREB: "DRB",
    REB: "TRB",
    AST: "AST",
    TOV: "TOV",
    STL: "STL",
    BLK: "BLK",
    BLKA: "BLKA",
    PF: "PF",
    PFD: "PFD",
    PTS: "PTS",
    PLUS_MINUS: "+/-",
    NBA_FANTASY_PTS: "N/A",
    DD2: "N/A",
    TD3: "N/A",
    WNBA_FANTASY_PTS: "N/A",
    // NBA_FANTASY_PTS: "FPTS",
    // DD2: "DD2",
    // TD3: "TP3",
    // WNBA_FANTASY_PTS: "WFPTS",
    GP_RANK: "N/A",
    W_RANK: "N/A",
    L_RANK: "N/A",
    W_PCT_RANK: "N/A",
    MIN_RANK: "N/A",
    FGM_RANK: "N/A",
    FGA_RANK: "N/A",
    FG_PCT_RANK: "N/A",
    FG3M_RANK: "N/A",
    FG3A_RANK: "N/A",
    FG3_PCT_RANK: "N/A",
    FTM_RANK: "N/A",
    FTA_RANK: "N/A",
    FT_PCT_RANK: "N/A",
    OREB_RANK: "N/A",
    DREB_RANK: "N/A",
    REB_RANK: "N/A",
    AST_RANK: "N/A",
    TOV_RANK: "N/A",
    STL_RANK: "N/A",
    BLK_RANK: "N/A",
    BLKA_RANK: "N/A",
    PF_RANK: "N/A",
    PFD_RANK: "N/A",
    PTS_RANK: "N/A",
    PLUS_MINUS_RANK: "N/A",
    NBA_FANTASY_PTS_RANK: "N/A",
    DD2_RANK: "N/A",
    TD3_RANK: "N/A",
    WNBA_FANTASY_PTS_RANK: "N/A",
    AVAILABLE_FLAG: "N/A",
};

export const headerMeaning = {
    WL: "Win-Loss",
    MIN: "Minutes Played",
    FGM: "Field Goals Made",
    FGA: "Field Goals Attempted",
    "FG%": "Field Goal Percentage",
    "3PM": "3 Pointers Made",
    "3PA": "3 Pointers Attempted",
    "3P%": "3 Point Percentage",
    FTM: "Free Throws Made",
    FTA: "Free Throws Attempted",
    "FT%": "Free Throw Percentage",
    ORB: "Offensive Rebounds",
    DRB: "Defensive Rebounds",
    TRB: "Total Rebounds",
    AST: "Assists",
    TOV: "Turnovers",
    STL: "Steals",
    BLK: "Blocks",
    BLKA: "Blocks Attempted",
    PF: "Personal Fouls",
    PFD: "Personal Fouls Drawn",
    PTS: "PTS",
    "+/-": "Plus-Minus",
    FPTS: "NBA Fantasy Points",
    DD2: "Double Doubles",
    TD3: "Triple Doubles",
    WFPTS: "WNBA Fantasy Points",
    // Following are uncertain
    // "GP_RANK": "Games Played Rank",
    // "W_RANK": "Win Rank",
    // "L_RANK": "Loss Rank",
    // "W_PCT_RANK": "Win Percentage Rank",
    // "MIN_RANK",
    // "FGM_RANK",
    // "FGA_RANK",
    // "FG_PCT_RANK",
    // "FG3M_RANK",
    // "FG3A_RANK",
    // "FG3_PCT_RANK",
    // "FTM_RANK",
    // "FTA_RANK",
    // "FT_PCT_RANK",
    // "OREB_RANK",
    // "DREB_RANK",
    // "REB_RANK",
    // "AST_RANK",
    // "TOV_RANK",
    // "STL_RANK",
    // "BLK_RANK",
    // "BLKA_RANK",
    // "PF_RANK",
    // "PFD_RANK",
    // "PTS_RANK",
    // "PLUS_MINUS_RANK",
    // "NBA_FANTASY_PTS_RANK",
    // "DD2_RANK",
    // "TD3_RANK",
    // "WNBA_FANTASY_PTS_RANK",
    // // What is this?
    // "AVAILABLE_FLAG",
};

export const defaultHeaders = [
    "DATE",
    "MATCH",
    "WL",
    "MIN",
    "FGM",
    "FGA",
    "FG%",
    "3PM",
    "3PA",
    "3P%",
    "FTM",
    "FTA",
    "FT%",
    "ORB",
    "DRB",
    "TRB",
    "AST",
    "TOV",
    "STL",
    "BLK",
    "BLKA",
    "PF",
    "PFD",
    "PTS",
    "+/-",
];

export const awardMapping = {'All-Defensive Team': 'All-Defensive Team',
'All-NBA': 'All-NBA',
'All-Rookie Team': 'All-Rookie Team',
'Hall of Fame Inductee': 'Hall of Fame',
'IBM Award': 'N/A',
'NBA All-Star Most Valuable Player': 'All-Star Most Valuable Player',
'NBA Defensive Player of the Year': 'Defensive Player of the Year',
'NBA Finals Most Valuable Player': 'Finals Most Valuable Player',
'NBA Most Valuable Player': 'Most Valuable Player',
'NBA Player of the Month': 'Player of the Month',
'NBA Player of the Week': 'Player of the Week',
'NBA Rookie of the Month': 'Rookie of the Month',
'NBA Rookie of the Year': 'Rookie of the Year',
'NBA Sporting News Most Valuable Player of the Year': 'N/A',
'NBA Sporting News Rookie of the Year': 'N/A',
'Olympic Gold Medal': 'Olympic Gold Medal'}