nba_teams = {
    'atlanta hawks': {'conference': 'Eastern', 'division': 'southeast'},
    'boston celtics': {'conference': 'Eastern', 'division': 'atlantic'},
    'brooklyn nets': {'conference': 'Eastern', 'division': 'atlantic'},
    'charlotte hornets': {'conference': 'Eastern', 'division': 'southeast'},
    'chicago bulls': {'conference': 'Eastern', 'division': 'central'},
    'cleveland cavaliers': {'conference': 'Eastern', 'division': 'central'},
    'detroit pistons': {'conference': 'Eastern', 'division': 'central'},
    'indiana pacers': {'conference': 'Eastern', 'division': 'central'},
    'miami heat': {'conference': 'Eastern', 'division': 'southeast'},
    'milwaukee bucks': {'conference': 'Eastern', 'division': 'central'},
    'new york knicks': {'conference': 'Eastern', 'division': 'atlantic'},
    'orlando magic': {'conference': 'Eastern', 'division': 'southeast'},
    'philadelphia 76ers': {'conference': 'Eastern', 'division': 'atlantic'},
    'toronto raptors': {'conference': 'Eastern', 'division': 'atlantic'},
    'washington wizards': {'conference': 'Eastern', 'division': 'southeast'},
    'dallas mavericks': {'conference': 'Western', 'division': 'southwest'},
    'denver nuggets': {'conference': 'Western', 'division': 'northwest'},
    'golden state warriors': {'conference': 'Western', 'division': 'pacific'},
    'houston rockets': {'conference': 'Western', 'division': 'southwest'},
    'los angeles clippers': {'conference': 'Western', 'division': 'pacific'},
    'los angeles lakers': {'conference': 'Western', 'division': 'pacific'},
    'memphis grizzlies': {'conference': 'Western', 'division': 'southwest'},
    'minnesota timberwolves': {'conference': 'Western', 'division': 'northwest'},
    'new orleans pelicans': {'conference': 'Western', 'division': 'southwest'},
    'oklahoma city thunder': {'conference': 'Western', 'division': 'northwest'},
    'phoenix suns': {'conference': 'Western', 'division': 'pacific'},
    'portland trail blazers': {'conference': 'Western', 'division': 'northwest'},
    'sacramento kings': {'conference': 'Western', 'division': 'pacific'},
    'san antonio spurs': {'conference': 'Western', 'division': 'southwest'},
    'utah jazz': {'conference': 'Western', 'division': 'northwest'}
}